"use client";

import { Sparkles } from "lucide-react";
import { ScenarioCard } from "./ScenarioCard";
import {
  MOCK_SCENARIOS,
  MOCK_BUSINESS_NAME,
  MOCK_BUSINESS_TAGLINE,
} from "@/lib/mock/simulation-scenarios";

interface ScenarioSelectionViewProps {
  onExplore: (id: string) => void;
}

export function ScenarioSelectionView({ onExplore }: ScenarioSelectionViewProps) {
  return (
    <div className="min-h-[calc(100vh-4rem)] px-6 py-10 max-w-5xl mx-auto">
      {/* Header */}
      <div className="mb-8 text-center">
        <h1 className="text-2xl font-bold tracking-tight">{MOCK_BUSINESS_NAME}</h1>
        <p className="text-sm text-muted-foreground mt-1">{MOCK_BUSINESS_TAGLINE}</p>
        <div className="mt-4 inline-flex items-center gap-2 rounded-full border border-border/50 bg-muted/30 px-4 py-1.5">
          <Sparkles className="h-3.5 w-3.5 text-amber-400" />
          <span className="text-xs text-muted-foreground">
            {MOCK_SCENARIOS.length} scenarios generated
          </span>
        </div>
      </div>

      {/* 2-column grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
        {MOCK_SCENARIOS.map((scenario) => (
          <ScenarioCard
            key={scenario.id}
            scenario={scenario}
            onExplore={onExplore}
          />
        ))}
      </div>

      {/* Footer */}
      <p className="mt-8 text-center text-xs text-muted-foreground">
        Generated by 6 AI agents analyzing your data
      </p>
    </div>
  );
}
