"use client";

import { Sparkles, Loader2, Plus, AlertTriangle } from "lucide-react";
import { ScenarioCard } from "./ScenarioCard";
import { Button } from "@/components/ui/button";
import type { ScenarioDetail } from "@/lib/types";

interface ScenarioSelectionViewProps {
  scenarios: ScenarioDetail[];
  businessName: string;
  businessTagline: string;
  onExplore: (id: string) => void;
  onGenerate?: () => void;
  isGenerating?: boolean;
  error?: string | null;
}

export function ScenarioSelectionView({
  scenarios,
  businessName,
  businessTagline,
  onExplore,
  onGenerate,
  isGenerating = false,
  error = null,
}: ScenarioSelectionViewProps) {
  return (
    <div className="min-h-[calc(100vh-4rem)] px-6 py-10 max-w-5xl mx-auto">
      {/* Header */}
      <div className="mb-8 text-center">
        <h1 className="text-2xl font-bold tracking-tight font-playfair">{businessName}</h1>
        <p className="text-sm text-muted-foreground mt-1">{businessTagline}</p>
        <div className="mt-4 inline-flex items-center gap-2 rounded-full border border-white/[0.08] bg-white/[0.03] px-4 py-1.5">
          <Sparkles className="h-3.5 w-3.5 text-amber-400" />
          <span className="text-xs text-muted-foreground">
            {scenarios.length} scenarios {scenarios.length > 0 ? "generated" : "available"}
          </span>
        </div>
      </div>

      {error ? (
        <div className="mb-6 flex items-center gap-2 rounded-lg border border-rose-500/30 bg-rose-500/5 p-3 text-sm text-rose-400">
          <AlertTriangle className="h-4 w-4 shrink-0" />
          {error}
        </div>
      ) : null}

      {/* Scenarios grid */}
      {scenarios.length > 0 ? (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
          {scenarios.map((scenario) => (
            <ScenarioCard
              key={scenario.id}
              scenario={scenario}
              onExplore={onExplore}
            />
          ))}
        </div>
      ) : (
        <div className="flex flex-col items-center justify-center py-16 text-center">
          <div className="flex h-16 w-16 items-center justify-center rounded-full bg-white/[0.05] mb-4">
            <Sparkles className="h-7 w-7 text-muted-foreground" />
          </div>
          <h3 className="font-semibold text-lg mb-2">No Scenarios Yet</h3>
          <p className="text-sm text-muted-foreground mb-6 max-w-md">
            Generate AI-powered strategic scenarios based on your business data, or
            create them manually.
          </p>
        </div>
      )}

      {/* Generate button */}
      {onGenerate ? (
        <div className="mt-8 flex justify-center gap-3">
          <Button
            onClick={onGenerate}
            disabled={isGenerating}
            className="bg-lime-400 text-forest-950 hover:bg-lime-300"
          >
            {isGenerating ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Generating Scenarios...
              </>
            ) : (
              <>
                <Sparkles className="mr-2 h-4 w-4" />
                {scenarios.length > 0 ? "Generate More Scenarios" : "Generate Scenarios with AI"}
              </>
            )}
          </Button>
        </div>
      ) : null}

      {/* Footer */}
      {scenarios.length > 0 ? (
        <p className="mt-8 text-center text-xs text-muted-foreground">
          Generated by 6 AI agents analyzing your data
        </p>
      ) : null}
    </div>
  );
}
